[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black = "#16161D"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#C8C093"

[colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#DCD7BA"

[colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "medium"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10
